name: frontend
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  data_table_2: ^2.3.8
  dio: ^4.0.6
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_conditional_rendering: ^2.0.0
  get: ^4.6.5
  jiffy: ^5.0.0
  pluto_grid: ^5.4.1
  shared_preferences: ^2.0.15
  printing: ^5.9.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/banners/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
    - family: Jannah
      fonts:
        - asset: assets/fonts/Jannah/Jannah.ttf
